# Generated by Django 6.0.6 on 2026-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField(db_column='dataNascimento')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('idRecepcionista', models.IntegerField(blank=True, db_column='idRecepcionista', null=True)),
                ('idAgenda', models.IntegerField(blank=True, db_column='idAgenda', null=True)),
                ('idProntuario', models.IntegerField(blank=True, db_column='idProntuario', null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'Paciente',
            },
        ),
    ]
